In [6]:
import numpy as np


In [7]:
inputs = [[1, 2, 3, 2.5], 
          [2, 5, -1, 2], 
          [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1], 
           [0.5, -0.91, 0.26, -0.5], 
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]

inputs_array = np.array(inputs)
weights_array = np.array(weights)
biases_array = np.array(biases)

output = np.dot(inputs_array, weights_array.T) + biases_array
print("Output: ", output)


Output:  [[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [8]:
weights2 = [[0.1, -0.14, 0.5], 
            [-0.5, 0.12, -0.33], 
            [-0.44, 0.73, -0.13]]
biases2 = [-1, 2, -0.5]

weights2_array = np.array(weights2)
biases2_array = np.array(biases2)

layer1_output = np.dot(inputs_array, weights_array.T) + biases_array
layer2_output = np.dot(layer1_output, weights2_array.T) + biases2_array

print("Layer 1 Output: ", layer1_output)
print("Layer 2 Output: ", layer2_output)


Layer 1 Output:  [[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
Layer 2 Output:  [[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]
