In [19]:
# Uncomment and run the below line only if nnfs is not installed
# !pip install nnfs

In [20]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()


In [21]:
class Layer_Dense: 
    def __init__(self, n_inputs, n_neurons): 
        self.weights = np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs): 
        self.output = np.dot(inputs, self.weights) + self.biases

X, y = spiral_data(samples=100, classes=3)
dense1 = Layer_Dense(2, 3)
dense1.forward(X)
print(dense1.output[:5])


[[ 0.          0.          0.        ]
 [-0.01047519  0.01139536 -0.00479835]
 [-0.02741484  0.03172915 -0.00869218]
 [-0.04218837  0.05266625 -0.00559127]
 [-0.05770768  0.0714014  -0.00894304]]
