In [15]:
import numpy as np


In [16]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

print(np.sum(A))


45


In [17]:
print(np.sum(A, axis = 0))
print(np.sum(A, axis = 0).shape)


[12 15 18]
(3,)


In [18]:
print(np.sum(A, axis = 1))
print(np.sum(A, axis = 1).shape)


[ 6 15 24]
(3,)


In [19]:
print(np.sum(A, axis = 0, keepdims = True))
print(np.sum(A, axis = 0, keepdims = True).shape)


[[12 15 18]]
(1, 3)


In [20]:
print(np.sum(A, axis = 1, keepdims = True))
print(np.sum(A, axis = 1, keepdims = True).shape)


[[ 6]
 [15]
 [24]]
(3, 1)


In [21]:
print(np.max(A, axis = 0))
print(np.max(A, axis = 1))


[7 8 9]
[3 6 9]
